### ISSUE TITLE
Error with Directly into CircleCi

### ISSUE THREAD

**Issue by anandwana001** [bufbuild/buf-example#3]
I checked the example and you had added a MAKE file and running through circleCi. I am trying to add this directly in my config.YAML but getting the error with few variables. I took the help from installation documentation of buf.build and created this script. 
Could you help me in understanding that? It's been 5 days, I am with this error. 

```
step_install_buf: &install_buf
  name: Download latest buf
  command: >
        get_latest_or_prerelease() {
             curl --silent "https://api.github.com/repos/$1/releases" |
             grep '"tag_name":' |
             sed -E 's/.*"([^"]+)".*/\1/'
        }

        BUFBUILD=$(get_latest_or_prerelease bufbuild/buf)
        BUFVERSION=${BUFBUILD%%[[:space:]]*}

        echo Using Bufbuild $BUFVERSION

        PROJECT="sample_project"
        UNAME_OS=$(shell uname -s)
        UNAME_ARCH=$(shell uname -m)
        CACHE_BASE=$(HOME)/.cache/$(PROJECT)
        CACHE=$(CACHE_BASE)/$(UNAME_OS)/$(UNAME_ARCH)
        CACHE_BIN=$(CACHE)/bin
        BINARY_NAME="buf"

        curl -sSL \
        "https://github.com/bufbuild/buf/releases/download/v$BUFVERSION/$BINARY_NAME-$(uname -s)-$(uname -m)" \
        -o "$CACHE_BIN/$BINARY_NAME"

        chmod +x "$CACHE_BIN/$BINARY_NAME"
```

I am getting error with these saying - `command not found`
```
UNAME_OS=$(shell uname -s)
UNAME_ARCH=$(shell uname -m)
CACHE_BASE=$(HOME)/.cache/$(PROJECT)
CACHE=$(CACHE_BASE)/$(UNAME_OS)/$(UNAME_ARCH)
CACHE_BIN=$(CACHE)/bin
```

**Comment by bufdev** [comment]
I can't debut the above script for you with the above info - can you run with `bash -x`?

**Comment by anandwana001** [comment]
ok, Could you help me understand this? How this `BUF` working? How about using https://hub.docker.com/r/bufbuild/buf directly?

```
BUF := $(CACHE_VERSIONS)/buf/$(BUF_VERSION)
$(BUF):
	@rm -f $(CACHE_BIN)/buf
	@mkdir -p $(CACHE_BIN)
ifeq ($(BUF_INSTALL_FROM_SOURCE),true)
	$(eval BUF_TMP := $(shell mktemp -d))
	cd $(BUF_TMP); go get github.com/bufbuild/buf/cmd/buf@$(BUF_VERSION)
	@rm -rf $(BUF_TMP)
else
	curl -sSL \
		"https://github.com/bufbuild/buf/releases/download/v$(BUF_VERSION)/buf-$(UNAME_OS)-$(UNAME_ARCH)" \
		-o "$(CACHE_BIN)/buf"
	chmod +x "$(CACHE_BIN)/buf"
endif
	@rm -rf $(dir $(BUF))
	@mkdir -p $(dir $(BUF))
	@touch $(BUF)
```

**Comment by bufdev** [comment]
We’d recommend checking the GNU make documentation for more details - we can’t support learning make itself here. for simple installation of Buf, see the installation documentation on https://buf.build

**Comment by bufdev** [comment]
Closing this unless there’s further concerns

**Comment by anandwana001** [comment]
I did this. Downloading the buf, moving to bin as per said in buf documentation. But now there is no output of the buf command, not even buf--help is showing in output.

```
curl -sSLO
https://github.com/bufbuild/buf/releases/download/v$BUFVERSION/buf-Linux-x86_64 > ~/buf
chmod +x ~/buf
sudo mv ~/buf /usr/local/bin/buf
buf check lint
```

**Comment by bufdev** [comment]
We cannot debug your development machine setup, I apologize. I would check to make sure `$BUFVERSION` is what you expect, as that's a common error in such `curl` usage.

**Comment by anandwana001** [comment]
I checked it's the latest one `v0.15.0`

**Comment by bufdev** [comment]
This really isn't the forum for this.

The binary operates as expected per the install instructions, I just tested it myself per the installation instructions. I'd recommend you debug your $BUFVERSION (does it have a prefix `v`? this would cause an error with the above `curl usage) and your `$PATH` variable.

**Comment by anandwana001** [comment]
The issue is resolved. 

Adding the script if in future someone comes up with the same problem. Installing `buf` to `CircleCi`, you can put below in your `config.yml`.

Downloading the `buf` release file using curl and as it uses `buf` key to run all commands, we need to change the file name to `buf` and made it executable. 
```
anchor_for_install_buf: &install_buf
  name: Download latest buf
  command: >
      get_latest_release() {
           curl --silent "https://api.github.com/repos/$1/releases" |
           grep '"tag_name":' |
           sed -E 's/.*"([^"]+)".*/\1/'
      }

      BUFBUILD=$(get_latest_release bufbuild/buf)

      BUFVERSION=${BUFBUILD%%[[:space:]]*}

      echo Using Bufbuild version $BUFVERSION

      curl -sSL
      https://github.com/bufbuild/buf/releases/download/$BUFVERSION/buf-$(uname -s)-$(uname -m) > /your/path/buf

      chmod +x /your/path/buf
```

Create steps, first install `bufbuild` and then use it as an executable command to do your work.
```
version: 2
jobs:
  linters:
    steps:
       - run:
          <<: *install_buf
       - run:
          name: BufBuild check proto files
          command: ./buf check lint && ./buf --version && echo "Bufbuild completed successfully"
```

**Comment by bufdev** [comment]
**The above is not correct, and should not be used** - you should pin to a version for CI, not always get the latest version, especially during beta.
